CREATE TABLE b_tk_main
(
    ID   INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
    SORT INT NOT NULL DEFAULT '100',
    PRIMARY KEY (ID)
);

CREATE TABLE b_tk_bots
(
    ID             INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
    DATE_CREATE    DATETIME NULL,
    DATE_MODIFY    DATETIME NULL,
    CREATED_BY_ID  INT (18) UNSIGNED NOT NULL,
    MODIFY_BY_ID   INT (18) UNSIGNED DEFAULT NULL,
    TITLE          VARCHAR(50) DEFAULT NULL,
    COMMENTS       TEXT        DEFAULT NULL,
    SEARCH_CONTENT MEDIUMTEXT NULL,
    ACTIVE         CHAR(1)     DEFAULT 'N',
    TOKEN          VARCHAR(50) DEFAULT NULL,
    PARSE_MODE     VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX          IX_B_TK_TITLE (TITLE),
    INDEX          IX_B_TK_1 (DATE_MODIFY),
    INDEX          IX_B_TK_2 (MODIFY_BY_ID),
    INDEX          IX_B_TK_3 (TOKEN),
    FULLTEXT       INDEX IX_B_TK_BOT_SEARCH (SEARCH_CONTENT)
);

/* Способы отправки событий */
/* Телеграм, Почта и Bitrix24 */
CREATE TABLE b_tk_type_event_send
(
    ID            INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
    DATE_CREATE   DATETIME NULL,
    DATE_MODIFY   DATETIME NULL,
    CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
    MODIFY_BY_ID  INT (18) UNSIGNED DEFAULT NULL,
    TITLE         VARCHAR(50) DEFAULT NULL,
    COMMENTS      TEXT        DEFAULT NULL,
    ACTIVE        CHAR(1)     DEFAULT 'N',
    TOKEN         VARCHAR(50) DEFAULT NULL,
    PARSE_MODE    VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX         IX_B_TK_TITLE (TITLE),
    INDEX         IX_B_TK_1 (DATE_MODIFY),
    INDEX         IX_B_TK_2 (MODIFY_BY_ID),
    INDEX         IX_B_TK_3 (TOKEN)
);

CREATE TABLE b_tk_events
(
    ID            INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
    DATE_CREATE   DATETIME NULL,
    DATE_MODIFY   DATETIME NULL,
    CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
    MODIFY_BY_ID  INT (18) UNSIGNED DEFAULT NULL,
    TITLE         VARCHAR(50) DEFAULT NULL,
    COMMENTS      TEXT        DEFAULT NULL,
    ACTIVE        CHAR(1)     DEFAULT 'N'
);

CREATE TABLE b_tk_logs
(
    ID            INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
    DATE_CREATE   DATETIME NULL,
    DATE_MODIFY   DATETIME NULL,
    CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
    MODIFY_BY_ID  INT (18) UNSIGNED DEFAULT NULL,
    TITLE         VARCHAR(50) DEFAULT NULL,
    TYPE_EVENT    VARCHAR(50) DEFAULT NULL
);

CREATE TABLE b_tk_chat_telegram
(
    ID             INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
    DATE_CREATE    DATETIME NULL,
    DATE_MODIFY    DATETIME NULL,
    CREATED_BY_ID  INT (18) UNSIGNED NOT NULL,
    MODIFY_BY_ID   INT (18) UNSIGNED DEFAULT NULL,
    TITLE          VARCHAR(50) DEFAULT NULL,
    COMMENTS       TEXT        DEFAULT NULL,
    ACTIVE         CHAR(1)     DEFAULT 'N',
    TOKEN          VARCHAR(50) DEFAULT NULL,
    PARSE_MODE     VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX          IX_B_TK_TITLE (TITLE),
    INDEX          IX_B_TK_1 (DATE_MODIFY),
    INDEX          IX_B_TK_2 (MODIFY_BY_ID),
    INDEX          IX_B_TK_3 (TOKEN)
);